# frozen_string_literal: true

Rails.application.routes.draw do
  get 'doc/create'
  post 'doc/new'
  delete 'doc/:id', to: 'doc#delete'
  delete 'logout', to: 'adm#delete'
  delete 'destroy_client/:id', to: 'clients#delete'
  get 'clients/new'
  post 'clients/new', to: 'clients#create'
  get 'documenti/index'
  get 'documenti/bo'
  get 'documenti/n'
  get 'documenti/u'
  get 'documenti/s'
  get 'service/index'
  get 'service/d1'
  get 'service/d2'
  get 'service/d3'
  get 'service/d4'
  get 'service/d5'
  delete 'orders/delete/:id', to: 'orders#delete'
  get 'documents', to: 'documents#all'
  get 'orders', to: 'orders#all'
  get 'adlog', to: 'adm#adlog'
  post 'adlog', to: 'adm#create_session'
  get 'home', to: 'home#index'
  get 'about', to: 'home#about'
  get 'contacts', to: 'home#contacts'
  get 'get_consult', to: 'home#getacall'
  post 'get_consult', to: 'home#create_order'
  get 'our_clients', to: 'home#ourclients'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
